# Generated by Django 5.2.1 on 2025-06-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', models.CharField(default='Welcome to SMARTPACE - Your Science Hub!', max_length=255)),
                ('announcement', models.TextField(blank=True, null=True)),
                ('daily_quote', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
