# Generated by Django 5.2.1 on 2025-06-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_number', models.CharField(help_text='e.g. 0712345678', max_length=20)),
                ('paybill_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, help_text='Optional thank-you or donation message')),
            ],
        ),
    ]
