# Generated by Django 5.2.1 on 2025-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_supportinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
