# Generated by Django 5.2.1 on 2025-06-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailyfact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_option',
            new_name='correct_answer',
        ),
    ]
