# Generated by Django 5.2.1 on 2025-06-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_approved_comment_updated_alter_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
