# Generated by Django 5.2.3 on 2025-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_options_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
