# Generated by Django 5.2.3 on 2025-07-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
