# Generated by Django 5.2.3 on 2025-07-02 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_quizresult_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='time_used_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
