# Generated by Django 5.2.3 on 2025-07-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_post_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_file',
            new_name='video',
        ),
    ]
