# Generated by Django 5.2.3 on 2025-07-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_profile_avatar_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
