# Generated by Django 5.2.3 on 2025-07-18 08:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_postmedia_image_alter_postmedia_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sound',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sound'),
        ),
    ]
