# Generated by Django 5.2.3 on 2025-07-29 20:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0043_homework_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='assigned_to',
            field=models.ManyToManyField(help_text='Select class(es) this homework is assigned to', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='instructions',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Homework instructions'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='answer_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Answer text'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='feedback',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Teacher feedback'),
        ),
    ]
