# Generated by Django 5.2.3 on 2025-07-30 07:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_homework_assigned_to_alter_homework_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='answer_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Answer Text'),
        ),
    ]
