# Generated by Django 5.2.3 on 2025-07-30 08:22

import cloudinary.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_homeworksubmission_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='graded',
        ),
        migrations.AddField(
            model_name='homework',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], default='Grade 8', max_length=20),
        ),
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='answer_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Your Answer'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], default='Grade 8', max_length=20),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.homework'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submitted_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.CreateModel(
            name='HomeworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.homework')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.homeworksubmission')),
            ],
        ),
    ]
