# Generated by Django 5.2.3 on 2025-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_homeworksubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
