# Generated by Django 5.2.3 on 2025-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_homeworksubmission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='mark_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the mark as a percentage (e.g., 87.50)', max_digits=5, null=True),
        ),
    ]
