# Generated by Django 5.2.3 on 2025-07-30 10:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_homeworksubmission_mark_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
