# Generated by Django 5.2.3 on 2025-08-04 15:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_homework_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='feedback',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
