# Generated by Django 5.2.3 on 2025-08-09 13:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_homeworksubmission_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Question Text'),
        ),
    ]
