# Generated by Django 5.2.3 on 2025-08-09 17:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_question_explanation_alter_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquote',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='dailyquote',
            name='quote',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
