# Generated by Django 5.2.3 on 2025-08-11 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_dailyquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquiz',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='dailyquiz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailyquiz',
            name='explanation',
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='explanation_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='explanation_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='explanation_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='explanation_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='option_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='option_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='option_c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='option_d',
            field=models.CharField(max_length=200),
        ),
    ]
