# Generated by Django 5.2.3 on 2025-08-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_dailyquiz_correct_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyquiz',
            old_name='explanation_a',
            new_name='explanation',
        ),
        migrations.RemoveField(
            model_name='dailyquiz',
            name='explanation_b',
        ),
        migrations.RemoveField(
            model_name='dailyquiz',
            name='explanation_c',
        ),
        migrations.RemoveField(
            model_name='dailyquiz',
            name='explanation_d',
        ),
    ]
