# Generated by Django 5.2.3 on 2025-08-11 20:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_rename_explanation_a_dailyquiz_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquiz',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
