# Generated by Django 5.2.3 on 2025-08-13 18:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_dailyquizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquizattempt',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
