# Generated by Django 5.2.3 on 2025-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_dailyquizattempt_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquizattempt',
            options={'ordering': ['-date_attempted']},
        ),
        migrations.AddField(
            model_name='dailyquizattempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyquizattempt',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
