# Generated by Django 5.2.3 on 2025-08-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_homework_pdf_file_alter_homework_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='grade',
        ),
    ]
