# Generated by Django 5.2.3 on 2025-08-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_homework_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_submissions/'),
        ),
    ]
