# Generated by Django 5.2.3 on 2025-08-14 19:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_homeworksubmission_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submitted_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
