# Generated by Django 5.2.3 on 2025-09-23 17:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_homeworksubmission_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquiz',
            name='explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Explanation'),
        ),
    ]
